feat: Authentication Staff
jabardigitalservice/groupware-whitelabel-api pull request #1
Opened 2022-03-17 10:13 UTC by fajarhikmal214

## Overview

### Feat
- feat: Add sign in with email and password endpoint
![image](https://user-images.githubusercontent.com/79292118/158920168-28af6621-2031-49b9-859d-bda982011bd0.png)
- feat: Add google authentication endpoint
![image](https://user-images.githubusercontent.com/79292118/158920642-4b63f2cf-f56a-4e7f-97ba-b8328fc7b0cf.png)
- feat: Add get me endpoint
![image](https://user-images.githubusercontent.com/79292118/158920462-c0843d2f-0205-4533-b5b0-d3cfc8665268.png)
- feat: Add refresh token endpoint
![image](https://user-images.githubusercontent.com/79292118/158920508-9f109948-f38b-43e1-abc1-ba3585b2290d.png)
- feat: Add sign out endpoint
![image](https://user-images.githubusercontent.com/79292118/158920575-26f65449-4c5c-4432-b473-80fb3eb459a7.png)

### Evidence
title: feat: add authentication staff
project: groupware white label
participants:  @sandisunandar99  @ayocodingit @rindibudiaramdhan @fajarhikmal214 @zidane-sc

2022-03-18 09:06 UTC, sandisunandar99 commented
gaes,, @zidane-sc @fajarhikmal214 saya sudah buatkan branch development. untuk kedepan nya flow development kita coba merge ke development dulu untuk staging dan main untuk production. 
ada proses review sebelum bisa merge ke development. 
dan temen2 nanti git flow nya bisa bikin branch per featur yg dibuat. ada kalo ada strategi lain silahkan kita open dengan hal2 baru 😄

2022-03-21 04:23 UTC, ayocodingit approved these changes
good job, dari aku cukup kang

cc: @sandisunandar99

2022-03-21 04:30 UTC, sandisunandar99 approved these changes

2022-03-21 05:08 UTC, rindibudiaramdhan approved these changes
Wow! nice description!

Mungkin judulnya bisa disesuaikan lagi yah, karena ada banyak API yang di PR kan disini , salah satunya logout.

kira2 apa ya judul yang sesuai? atau feat: login staff ini sudah sesuai?

2022-03-21 05:13 UTC, zidane-sc requested changes

2022-03-21 06:28 UTC, fajarhikmal214 commented on src/auth/auth.controller.ts
> +@Controller('v1/auth/users')
> Wow! nice description!
> 
> Mungkin judulnya bisa disesuaikan lagi yah, karena ada banyak API yang di PR kan disini , salah satunya logout.
> 
> kira2 apa ya judul yang sesuai? atau feat: login staff ini sudah sesuai?

Kalau **feat: authentication staff**  cukup mendeskripsikan gak ya Kang ?

2022-03-21 06:29 UTC, fajarhikmal214 commented
> Wow! nice description!
> 
> Mungkin judulnya bisa disesuaikan lagi yah, karena ada banyak API yang di PR kan disini , salah satunya logout.
> 
> kira2 apa ya judul yang sesuai? atau feat: login staff ini sudah sesuai?

Kalau jadi **feat: authentication staff** cukup mendeskripsikan gak ya Kang ?

2022-03-21 06:53 UTC, zidane-sc approved these changes
Nicee 👍🏻

2022-03-21 07:09 UTC, merged