Feat/get main duties by job title id
jabardigitalservice/groupware-whitelabel-api pull request #27
Opened 2022-04-06 05:33 UTC by zidane-sc

## Overview

- Feat: add a new endpoint get main duties by job title id

## Evidence

- title: get main duties by job title id
- project: Digiteam
- participants: @zidane-sc  @fajarhikmal214

2022-04-06 06:08 UTC, ayocodingit approved these changes

2022-04-07 00:57 UTC, fajarhikmal214 requested changes
Naming file nya kebab-case biar serentak

2022-04-07 05:05 UTC, sandisunandar99 approved these changes

2022-04-08 01:15 UTC, fajarhikmal214 approved these changes

2022-04-08 01:34 UTC, merged