Feat/get list user
jabardigitalservice/groupware-whitelabel-api pull request #3
Opened 2022-03-21 10:36 UTC by zidane-sc

### Feat

- #### feat: add get users endpoint
  **Purpose:**  this endpoint will be consumed in Frontend to fetching data for showing in multiple select
 ![image](https://user-images.githubusercontent.com/67301786/159244295-862662a0-0cbf-4269-98f9-33feea90562c.png)

### Unit Testing Result
![image](https://user-images.githubusercontent.com/67301786/159244562-7a5b7828-68bb-4335-acc1-5936c3cff7bd.png)

### Evidence
title: get list user
project: groupware white label
participant: @zidane-sc

2022-03-22 02:44 UTC, ayocodingit approved these changes

2022-03-22 03:13 UTC, sandisunandar99 requested changes

2022-03-22 03:13 UTC, sandisunandar99 commented on src/users/repositories/user.repository.ts
> +  getUsers(getUsersFilterDto: GetUsersFilterDto): Promise<User[]> {
btw, untuk proses query data kalo bisa pake try catch ya, suapaya nnti kita bisa tau catch data kalo ada error di proses nya.

ada contoh bagus yang sudah di implementasikan. dan ini konsepnya centralize handler error,, bisa cek dsini

https://github.com/jabardigitalservice/dedi-core-service/blob/main/src/handler/exception.ts

atau bisa bantu jawab mangs @ayocodingit 😄

2022-03-22 03:16 UTC, rindibudiaramdhan commented on src/users/repositories/user.repository.ts
> +  getUsers(getUsersFilterDto: GetUsersFilterDto): Promise<User[]> {
oiya mang @sandisunandar99 , terkait error handling ini, API ini sudah disetup di sentry belum ya?

2022-03-22 03:18 UTC, ayocodingit commented on src/users/repositories/user.repository.ts
> +  getUsers(getUsersFilterDto: GetUsersFilterDto): Promise<User[]> {
oh iya betul ini untuk handle error nya belum ada kang @fajarhikmal214, setup sentry error sama sentry performance nya 😄

2022-03-22 03:27 UTC, sandisunandar99 commented on src/users/repositories/user.repository.ts
> +  getUsers(getUsersFilterDto: GetUsersFilterDto): Promise<User[]> {
oia integrasi ke  sentry .. sebentar sya buatkan projek nya dlu ,, nanti saya invite antum2 disini ,, 😆 👍

2022-03-22 03:29 UTC, sandisunandar99 commented on src/users/repositories/user.repository.ts
> +  getUsers(getUsersFilterDto: GetUsersFilterDto): Promise<User[]> {
oia nnti pelajari cara logging menggunakan senty ya kang @fajarhikmal214 @zidane-sc 
dan kalo belum ada akun sentry, silahkan daftar dlu aja,, nnti kalo udah kabari username/email nya disni atau di matermos..

2022-03-22 03:49 UTC, sandisunandar99 commented on src/users/repositories/user.repository.ts
> +  getUsers(getUsersFilterDto: GetUsersFilterDto): Promise<User[]> {
udah ku buatin tinggal lanjut gas,, 

![Screen Shot 2022-03-22 at 10 48 54](https://user-images.githubusercontent.com/6767399/159404171-bc1c5004-3aa5-4562-9ba8-1c849e384b1f.png)

2022-03-22 03:50 UTC, sandisunandar99 commented on src/users/repositories/user.repository.ts
> +  getUsers(getUsersFilterDto: GetUsersFilterDto): Promise<User[]> {
dokumentasi bisa di liat disni 


https://mantosz.medium.com/use-sentry-with-nestjs-6d255027d3e1

2022-03-22 07:22 UTC, fajarhikmal214 commented on src/users/repositories/user.repository.ts
> +  getUsers(getUsersFilterDto: GetUsersFilterDto): Promise<User[]> {
Kang ini email akun sentry saya fajarhikmal214@gmail.com

2022-03-22 07:25 UTC, zidane-sc commented on src/users/repositories/user.repository.ts
> +  getUsers(getUsersFilterDto: GetUsersFilterDto): Promise<User[]> {
Email akun sentry: zidanesc02@gmail.com

cc: @sandisunandar99

2022-03-23 03:53 UTC, sandisunandar99 approved these changes
GASKEEENN....

2022-03-23 03:54 UTC, merged