Feat: Attendance Staff
jabardigitalservice/groupware-whitelabel-api pull request #4
Opened 2022-03-22 23:50 UTC by fajarhikmal214

## Overview

### Feat

- feat: Add check in endpoint
![image](https://user-images.githubusercontent.com/79292118/159592779-be262dc9-38a7-41e1-9cde-c76cbe939293.png)
- feat: Add check out endpoint
![image](https://user-images.githubusercontent.com/79292118/159593831-e8693fca-f46c-412f-878e-e87a31c4e904.png)
- feat: Add is checked in endpoint
![image](https://user-images.githubusercontent.com/79292118/159593883-fd7f12fd-800b-43d7-a823-e2ddde7e3a6a.png)
- fear: Add is checked out endpoint
![image](https://user-images.githubusercontent.com/79292118/159593921-2ed4b10a-4f22-47fd-a09e-902cf4468dbb.png)

### Unit Test Result
![image](https://user-images.githubusercontent.com/79292118/159595095-d28a597d-f324-42a0-8d49-f36234c5b13d.png)

### Evidence

title: feat: add attendance staff
project: groupware white label
participants: @fajarhikmal214

2022-03-22 23:53 UTC, fajarhikmal214 commented
Kang @sandisunandar99 punten satu lagi PR sebelum memperbaiki design path folder dan setup lainnya

2022-03-23 03:06 UTC, sandisunandar99 commented
> Kang @sandisunandar99 punten satu lagi PR sebelum memperbaiki design path folder dan setup lainnya

okey kang,,

2022-03-23 03:20 UTC, ayocodingit commented
kang @fajarhikmal214 btw issue time ini bisa related gak yah issue timezone 😄 

https://github.com/jabardigitalservice/portal-jabar-services/issues/8#issue-970201360

2022-03-23 03:23 UTC, sandisunandar99 requested changes

2022-03-23 03:23 UTC, sandisunandar99 commented on package.json
> +    "start": "SET TZ=Asia/Jakarta && nest start",
btw ini kenapa perlu di set timezone ya di npm run nya? 
local timezone nya ga ke bawa ya?

2022-03-23 03:23 UTC, sandisunandar99 commented on src/common/helpers/date.helper.ts
> +const date = new Date(dateString);
kang untuk Date ini mungkin bisa pake packge aja supaya lebih mudah dan simpel,, saya biasanya pake ini

https://momentjs.com/

dan untuk yg coding di bawahnya juga yg ada keterkaitan dengan date, time bisa pake package ini juga,, 👍

2022-03-23 04:20 UTC, fajarhikmal214 commented on package.json
> +    "start": "SET TZ=Asia/Jakarta && nest start",
> kang @fajarhikmal214 btw issue time ini bisa related gak yah issue timezone 😄
> 
> [jabardigitalservice/portal-jabar-services#8 (comment)](https://github.com/jabardigitalservice/portal-jabar-services/issues/8#issue-970201360)

Kalau be tidak menghandle timezone user, sebaiknya format timestamp yang disimpan di database itu seperti apa ya Kang ? apa perlu menyimpan timezone atau tidak ya Kang ? 
seperti 2022-03-20 13:49:55.417006 dibanding 2022-03-23 11:14:19.276723+07

2022-03-23 04:21 UTC, fajarhikmal214 commented
> kang @fajarhikmal214 btw issue time ini bisa related gak yah issue timezone 😄
> 
> [jabardigitalservice/portal-jabar-services#8 (comment)](https://github.com/jabardigitalservice/portal-jabar-services/issues/8#issue-970201360)

Kalau be tidak menghandle timezone user, sebaiknya format timestamp yang disimpan di database itu seperti apa ya Kang ? apa perlu menyimpan timezone atau tidak ya Kang @ayocodingit  ?
seperti 2022-03-20 13:49:55.417006 dibanding 2022-03-23 11:14:19.276723+07

2022-03-23 04:34 UTC, fajarhikmal214 commented on src/common/helpers/date.helper.ts
> +const date = new Date(dateString);
oke Kang akan diperbaiki pakai momentjs

2022-03-23 04:38 UTC, fajarhikmal214 commented on package.json
> +    "start": "SET TZ=Asia/Jakarta && nest start",
iya Kang local timezone nya gak ke bawa, jadi seperti berbeda 7 jam dari data di database (timezone UTC yang netral)

Apa di be tidak perlu effort untuk menyesuaikan response timestamp ya Kang ? jadi di fe aja di sesuaikan dengan timezone usernya atau bagaimana ya Kang @sandisunandar99  ?

2022-03-23 04:51 UTC, ayocodingit commented
> > kang @fajarhikmal214 btw issue time ini bisa related gak yah issue timezone 😄
> > [jabardigitalservice/portal-jabar-services#8 (comment)](https://github.com/jabardigitalservice/portal-jabar-services/issues/8#issue-970201360)
> 
> Kalau be tidak menghandle timezone user, sebaiknya format timestamp yang disimpan di database itu seperti apa ya Kang ? apa perlu menyimpan timezone atau tidak ya Kang @ayocodingit ? seperti 2022-03-20 13:49:55.417006 dibanding 2022-03-23 11:14:19.276723+07

iya kalau backend itu sebaiknya timezone nya 00:00 waktu karena deploy kita flexibel, nah untuk proses +07:00 itu ada di frontend nya kang

2022-03-23 05:03 UTC, fajarhikmal214 commented
> > > kang @fajarhikmal214 btw issue time ini bisa related gak yah issue timezone 😄
> > > [jabardigitalservice/portal-jabar-services#8 (comment)](https://github.com/jabardigitalservice/portal-jabar-services/issues/8#issue-970201360)
> > 
> > 
> > Kalau be tidak menghandle timezone user, sebaiknya format timestamp yang disimpan di database itu seperti apa ya Kang ? apa perlu menyimpan timezone atau tidak ya Kang @ayocodingit ? seperti 2022-03-20 13:49:55.417006 dibanding 2022-03-23 11:14:19.276723+07
> 
> iya kalau backend itu sebaiknya timezone nya 00:00 waktu karena deploy kita flexibel, nah untuk proses +07:00 itu ada di frontend nya kang

Kalau terkait response timestamp yang berbeda 7 jam dari data di database (kemungkinan local timezone nya gak ke bawa) 

apakah akan menjadi masalah gak ya Kang @ayocodingit ketika di consume oleh FE ? 
Atau memang seperti itu ? Atau harus effort disamain di BE ?

2022-03-23 06:19 UTC, ayocodingit commented
> > > > kang @fajarhikmal214 btw issue time ini bisa related gak yah issue timezone 😄
> > > > [jabardigitalservice/portal-jabar-services#8 (comment)](https://github.com/jabardigitalservice/portal-jabar-services/issues/8#issue-970201360)
> > > 
> > > 
> > > Kalau be tidak menghandle timezone user, sebaiknya format timestamp yang disimpan di database itu seperti apa ya Kang ? apa perlu menyimpan timezone atau tidak ya Kang @ayocodingit ? seperti 2022-03-20 13:49:55.417006 dibanding 2022-03-23 11:14:19.276723+07
> > 
> > 
> > iya kalau backend itu sebaiknya timezone nya 00:00 waktu karena deploy kita flexibel, nah untuk proses +07:00 itu ada di frontend nya kang
> 
> Kalau terkait response timestamp yang berbeda 7 jam dari data di database (kemungkinan local timezone nya gak ke bawa)
> 
> apakah akan menjadi masalah gak ya Kang @ayocodingit ketika di consume oleh FE ? Atau memang seperti itu ? Atau harus effort disamain di BE ?

responsenya pun biar kan UTC 00 kang @fajarhikmal214

2022-03-23 06:49 UTC, sandisunandar99 commented on package.json
> +    "start": "SET TZ=Asia/Jakarta && nest start",
mending jangan perlu dulu kang apa adanya. soalnya nnti mah kalo sudah di server pasti harus ngikutin timestamp servernya.

2022-03-23 06:50 UTC, sandisunandar99 commented on src/common/helpers/date.helper.ts
> +const date = new Date(dateString);
okey2,, nuhun2 ya,, 👍

2022-03-23 08:48 UTC, fajarhikmal214 commented on package.json
> +    "start": "SET TZ=Asia/Jakarta && nest start",
oke kang baik

2022-03-23 09:50 UTC, fajarhikmal214 commented
O

> > > > > kang @fajarhikmal214 btw issue time ini bisa related gak yah issue timezone 😄
> > > > > [jabardigitalservice/portal-jabar-services#8 (comment)](https://github.com/jabardigitalservice/portal-jabar-services/issues/8#issue-970201360)
> > > > 
> > > > 
> > > > Kalau be tidak menghandle timezone user, sebaiknya format timestamp yang disimpan di database itu seperti apa ya Kang ? apa perlu menyimpan timezone atau tidak ya Kang @ayocodingit ? seperti 2022-03-20 13:49:55.417006 dibanding 2022-03-23 11:14:19.276723+07
> > > 
> > > 
> > > iya kalau backend itu sebaiknya timezone nya 00:00 waktu karena deploy kita flexibel, nah untuk proses +07:00 itu ada di frontend nya kang
> > 
> > 
> > Kalau terkait response timestamp yang berbeda 7 jam dari data di database (kemungkinan local timezone nya gak ke bawa)
> > apakah akan menjadi masalah gak ya Kang @ayocodingit ketika di consume oleh FE ? Atau memang seperti itu ? Atau harus effort disamain di BE ?
> 
> responsenya pun biar kan UTC 00 kang @fajarhikmal214

Oke kang baik terima kasih

2022-03-23 10:30 UTC, sandisunandar99 requested changes

2022-03-23 10:30 UTC, sandisunandar99 commented on src/models/attendances/attendances.repository.ts
> +    const attendance = await this.createQueryBuilder('attendances')
maaf ini ketinggalan 😆 ,, untuk proses query jngan lupa pake try catch ya.. 
btw berlaku untuk yg lain juga yg di bawah,, 👍

2022-03-24 01:09 UTC, fajarhikmal214 commented on src/models/attendances/attendances.repository.ts
> +    const attendance = await this.createQueryBuilder('attendances')
oke Kang @sandisunandar99 sudah

2022-03-24 01:10 UTC, fajarhikmal214 commented
Kang @ayocodingit @rindibudiaramdhan @sandisunandar99 izin minta review nya kembali, terima kasih

2022-03-24 03:08 UTC, ayocodingit approved these changes

2022-03-24 03:10 UTC, sandisunandar99 approved these changes

2022-03-24 03:10 UTC, sandisunandar99 commented
gass @fajarhikmal214

2022-03-24 03:16 UTC, rindibudiaramdhan approved these changes
next nya, bisa disepakati atau didiskusikan ya terkait size dari PR ini.
Saran saya bisa dipisah per API nya. 🙏

2022-03-24 03:16 UTC, fajarhikmal214 commented
> next nya, bisa disepakati atau didiskusikan ya terkait size dari PR ini. Saran saya bisa dipisah per API nya. 🙏

iya kang kedepannya akan per fitur / endpoint, mohon maaf kang kebanyakan

2022-03-24 03:35 UTC, zidane-sc approved these changes

2022-03-24 03:39 UTC, merged