Feat/setup sentry loggin error and performance
jabardigitalservice/groupware-whitelabel-api pull request #7
Opened 2022-03-25 06:48 UTC by zidane-sc

## Overview

- add sentry for logging error
- add sentry for logging performance

## Evidence

- title: setup sentry loggin error and performance
- project: Digiteam
- participants: @zidane-sc @sandisunandar99 @ayocodingit @fajarhikmal214

2022-03-25 07:13 UTC, ayocodingit approved these changes

2022-03-25 07:19 UTC, sandisunandar99 commented on src/config.schema.ts
> +  SENTRY_DSN: Joi.string().required(),
ini dsn nya udah ada kang?

2022-03-25 07:22 UTC, zidane-sc commented on src/config.schema.ts
> +  SENTRY_DSN: Joi.string().required(),
masih pakai punya saya kang

2022-03-25 07:25 UTC, sandisunandar99 commented on src/config.schema.ts
> +  SENTRY_DSN: Joi.string().required(),
oh ,, oke2,, nnti di coba dlu ya,, kalo udah jalan di sentry sendri, nnti dsn nya minta aja ya ke saya buat yg ke JDS

2022-03-25 07:25 UTC, sandisunandar99 approved these changes

2022-03-25 07:28 UTC, zidane-sc commented on src/config.schema.ts
> +  SENTRY_DSN: Joi.string().required(),
Okee sip terimakasih kang

2022-03-25 07:33 UTC, fajarhikmal214 requested changes

2022-03-25 07:33 UTC, fajarhikmal214 commented on src/common/exceptions/http-error.filter.ts
> +    timeStamp: new Date().toString(),
Pakai momentjs

2022-03-28 02:36 UTC, fajarhikmal214 approved these changes

2022-03-28 02:37 UTC, merged