Sprint 1: Setup Docker
jabardigitalservice/groupware-whitelabel-api pull request #9
Opened 2022-03-27 23:35 UTC by fajarhikmal214

## Overview

- Setup Docker

## Evidence

- title: sprint 1: setup docker
- project: Digiteam
- participants: @fajarhikmal214 @zidane-sc

2022-03-28 01:37 UTC, ayocodingit commented
Kang @fajarhikmal214 kalau hasil build image nya berapa mb size nya?

2022-03-28 01:40 UTC, fajarhikmal214 commented
> Kang @fajarhikmal214 kalau hasil build image nya berapa mb size nya?

578.92 MB Kang

2022-03-28 01:58 UTC, ayocodingit requested changes

2022-03-28 01:58 UTC, ayocodingit commented on docker/Dockerfile
> +COPY . .
Untuk production sebaiknya gunakan multi stage kang, bisa di contoh yah image [disini](https://github.com/jabardigitalservice/dedi-core-service/blob/main/docker/Dockerfile)

Tujuannya untuk re size image file yang tidak di perlukan saat production, contoh kecilnya saat production tidak butuh jest, atau file bertipe typescript 😁

2022-03-28 01:58 UTC, ayocodingit commented on docker-compose.yml
> +      - ${APP_PORT}:${APP_PORT}
Ini langsung aja kang ikutin yang ada di dockerfile nya, karena semua image port nya sudah dibuat hardcode
```suggestion
      - 3000:3000
```

2022-03-28 02:02 UTC, ayocodingit commented
> > Kang @fajarhikmal214 kalau hasil build image nya berapa mb size nya?
> 
> 578.92 MB Kang @ayocodingit 

Wah black hole yah, coba rubah yah jadi multistage docker nya agar tidak semua ikut ter install, seharusnya aku liat dependency nya tidak terlalu berat bisa lah 40mb-70mb kang @fajarhikmal214 💪💪💪

2022-03-28 04:54 UTC, sandisunandar99 commented on docker/Dockerfile
> +COPY . .
atau bisa saat install packge di bedakan aja,, antara package yg akan di install di prod dan local
contoh nya bisa menambahkan `RUN npm ci --only=production` ini. 
dan ini di sesuaikan juga di package.json nya kalo `--only=production` maka yg di install itu kurang lebih package yng ada di `dependencies` aja.. tapi kalo `--only=development` maka yg di install itu pakage yg ada di `dependencies dan devDependencies`. mungkin bisa cek di package.json ada object itu,, 
selebih nya mau multistage atau single stage boleh2 aja,, nanti akang2 bisa membedakan mana proses yang compiling nya lebih lmayan cpet
cc : @fajarhikmal214 @zidane-sc @ayocodingit 

referensi mungkin saya nyontek didiieeuuu,, 😄 
https://github.com/sandisunandar99/docker-nestjs-starter

2022-03-28 07:55 UTC, fajarhikmal214 commented
> 

Masih di angka 111.17 MB Kang

2022-03-28 07:55 UTC, fajarhikmal214 commented
> > > Kang @fajarhikmal214 kalau hasil build image nya berapa mb size nya?
> > 
> > 
> > 578.92 MB Kang @ayocodingit
> 
> Wah black hole yah, coba rubah yah jadi multistage docker nya agar tidak semua ikut ter install, seharusnya aku liat dependency nya tidak terlalu berat bisa lah 40mb-70mb kang @fajarhikmal214 💪💪💪
> 
> Fyi yang desa digital size image nya, 41 MB an

Masih di angka 111.17 MB Kang @ayocodingit 

cc : @sandisunandar99

2022-03-28 08:08 UTC, ayocodingit commented
> > > > Kang @fajarhikmal214 kalau hasil build image nya berapa mb size nya?
> > > 
> > > 
> > > 578.92 MB Kang @ayocodingit
> > 
> > 
> > Wah black hole yah, coba rubah yah jadi multistage docker nya agar tidak semua ikut ter install, seharusnya aku liat dependency nya tidak terlalu berat bisa lah 40mb-70mb kang @fajarhikmal214 💪💪💪
> > Fyi yang desa digital size image nya, 41 MB an
> 
> Masih di angka 111.17 MB Kang @ayocodingit
> 
> cc : @sandisunandar99

boleh dipush terlebih dahulu dockerfile nya kang,

2022-03-29 00:54 UTC, fajarhikmal214 commented
> > > > > Kang @fajarhikmal214 kalau hasil build image nya berapa mb size nya?
> > > > 
> > > > 
> > > > 578.92 MB Kang @ayocodingit
> > > 
> > > 
> > > Wah black hole yah, coba rubah yah jadi multistage docker nya agar tidak semua ikut ter install, seharusnya aku liat dependency nya tidak terlalu berat bisa lah 40mb-70mb kang @fajarhikmal214 💪💪💪
> > > Fyi yang desa digital size image nya, 41 MB an
> > 
> > 
> > Masih di angka 111.17 MB Kang @ayocodingit
> > cc : @sandisunandar99
> 
> boleh dipush terlebih dahulu dockerfile nya kang,

Masih 192MB Kang, tapi yang desa digital coba saya run build image nya 144MB ya Kang @ayocodingit  ? mungkin saya ada yang kelewat ? 

cc : @sandisunandar99

2022-03-29 02:22 UTC, ayocodingit approved these changes

2022-03-29 02:49 UTC, sandisunandar99 approved these changes

2022-03-29 02:55 UTC, zidane-sc approved these changes

2022-03-29 02:57 UTC, merged